eventplus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls'))
]

landingpage/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "landingpage"
urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='landingpage/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/register/', views.pilihTipe, name='pilihTipe'),
    path('accounts/register/organizer', views.registerOrganizer, name='registerOrginazer'),
    path('accounts/register/pengunjung', views.registerPengunjung, name='registerPengunjung'),
    path('event/', views.event, name='event'),
    path('tambahevent/', views.tambahevent, name='tambahevent'),
    # path('tambahkelastiket/', views.tambahkelastiket, name='tambahkelastiket')
]

landingpage/models.py
from django.db import models

# Create your models here.

landingpage/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.contrib.auth.forms import UserCreationForm
from django.db import connection
import datetime

def index(request):
    cursor = connection.cursor()
    # cursor.execute("select * from transaksi")
    # row = cursor.fetchall()
    if request.user.is_authenticated:
        email = request.user.username
        cursor.execute("select * from organizer where email='"+email+"'")
        dataUser = cursor.fetchall()
        print(dataUser)
        if dataUser == []:
            tipe = "Pengguna"
            return render(request, "landingpage/index.html", {'tipe':tipe})
        else:
            tipe = "Organizer"
            cursor.execute("select e.id_event, e.nama, e.tanggal_mulai, e.tanggal_selsai, e.jam_mulai, e.jam_selesai, e.deskripsi, e.kapasitas_total, e.kapasitas_total_tersedia, t.nama_tipe from event e, tipe t where email_organizer='"+email+"' and e.id_tipe = t.id_tipe")
            dataEvent = cursor.fetchall()
            print(dataEvent)
            return render(request, "landingpage/index.html", {'tipe':tipe, 'dataEvent':dataEvent})
    return render(request, "landingpage/index.html")

def event(request):
    cursor = connection.cursor()
    cursor.execute("select e.id_event, e.nama, e.tanggal_mulai, e.tanggal_selsai, e.jam_mulai, e.jam_selesai, e.deskripsi, e.kapasitas_total, e.kapasitas_total_tersedia, t.nama_tipe, e.email_organizer from event e, tipe t where e.id_tipe = t.id_tipe")
    row = cursor.fetchall()
    return render(request, "landingpage/event.html", {'row': row})

def tambahevent(request):
    if request.user.is_authenticated:
        email = request.user.username
        if request.method == "POST":
            name = request.POST['name']
            tglmulai = request.POST['tglmulai']
            tglselesai = request.POST['tglselesai']
            jammulai = request.POST['jammulai']
            jamselesai = request.POST['jamselesai']
            deskripsi = request.POST['deskripsi']
            tipe = request.POST['tipe']
            cursor = connection.cursor()
            cursor.execute("INSERT INTO event (nama, tanggal_mulai, tanggal_selsai, jam_mulai, jam_selesai, deskripsi, kapasitas_total, kapasitas_total_tersedia, id_tipe, email_organizer) VALUES ('"+name+"', '"+tglmulai+"', '"+tglselesai+"', '"+jammulai+"', '"+jamselesai+"', '"+deskripsi+"', 0, 0, '"+tipe+"', '"+email+"');")
            return redirect("../")
        else:
            cursor = connection.cursor()
            cursor.execute("select * from tipe")
            row = cursor.fetchall()
        return render(request, "landingpage/tambahevent.html", {'row': row})

def pilihTipe(request):
    return render(request, "landingpage/pilihTipe.html")

def registerPengunjung(request):
    if request.method == 'POST':
        print(request.POST)
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            cursor = connection.cursor()
            email = request.POST['username']
            password = request.POST['password1']
            namaDepan = request.POST['namaDepan']
            namaBelakang = request.POST['namaBelakang']
            cursor.execute(f"INSERT INTO pengguna (email, password) VALUES ('{email}', '{password}')")
            cursor.execute(f"INSERT INTO pengunjung (email, nama_depan, nama_belakang) VALUES ('{email}', '{namaDepan}', '{namaBelakang}')")
            username = form.cleaned_data.get('username')
            messages.success(request, f'Selamat, Akun {username} telah dibuat!')
            print(username)
            return redirect('landingpage:login')
        else:
            messages.error(request, 'Wahh sepertinya ada yang salah di pengisian data mu!')
            return render(request, 'landingpage/registerPengunjung.html', {"form" : form})
    else:
        form = UserCreationForm()
        return render(request, "landingpage/registerPengunjung.html", {"form" : form})

def registerOrganizer(request):
    if request.method == 'POST':
        print(request.POST)
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            cursor = connection.cursor()
            email = request.POST['username']
            password = request.POST['password1']
            namaDepan = request.POST['namaDepan']
            nomor = request.POST['nomor']
            tipeOrgan = request.POST.get('tipeOrgan', False)
            cursor.execute(f"INSERT INTO pengguna (email, password) VALUES ('{email}', '{password}')")
            cursor.execute(f"INSERT INTO organizer (email, npwp) VALUES ('{email}', '{nomor}')")
            if (tipeOrgan == "individu"):
                namaBelakang = request.POST['namaBelakang']
                cursor.execute(f"INSERT INTO individu (email, no_ktp, nama_depan, nama_belakang) VALUES ('{email}', '{nomor}', '{namaDepan}', '{namaBelakang}')")
            elif (tipeOrgan == "perusahaan"):
                cursor.execute(f"INSERT INTO perusahaan (email, nama) VALUES ('{email}', '{namaDepan}')")
            username = form.cleaned_data.get('username')
            messages.success(request, f'Selamat, Akun {username} telah dibuat!')
            print(username)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Selamat, Akun {username} telah dibuat!')
            print(username)
            return redirect('landingpage:login')
        else:
            messages.error(request, 'Wahh sepertinya ada yang salah di pengisian data mu!')
            return render(request, 'landingpage/registerOrganizer.html', {"form" : form})
    else:
        form = UserCreationForm()
        return render(request, "landingpage/registerOrganizer.html", {"form" : form})

def loginSuccessMessage(sender, user, request, **kwargs):
    messages.success(request, "Halo " + user.username + "! Kamu berhasil Login.")

def logoutSuccessMessage(sender, user, request, **kwargs):
    messages.success(request, "Terimakasih " + user.username + " telah berkunjung. Dadah!")

user_logged_in.connect(loginSuccessMessage)
user_logged_out.connect(logoutSuccessMessage)

templates/landingpage/event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <br>
    <br>
    <a href="../">
        <button>
            Back
        </button>
    </a>
    <br>
    <br>
    <h1>Daftar Event</h1>
    <table style="border-spacing: 15px;">
        <tr>
            <th>
                ID Event
            </th>
            <th>
                Nama Event
            </th>
            <th>
                Tanggal Mulai
            </th>
            <th>
                Tanggal Selesai
            </th>
            <th>
                Jam Mulai
            </th>
            <th>
                Jam Selesai
            </th>
            <th>
                Deskripsi
            </th>
            <th>
                Kapasitas Total
            </th>
            <th>
                Kapasitas Total Tersedia
            </th>
            <th>
                Tipe Event
            </th>
            <th>
                Email Organizer
            </th> 
        </tr>
        {% for i in row %}
        <tr>
            {% for j in i %}
            {% if j == None %}
            <td>0</td>
            {% else %}
            <td>{{j}}</td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <!-- <h4>{{i}}</h4> -->
</body>
</html>

templates/landingpage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event+</title>
</head>
<body>
    <br>
    <br>
    <br>
    {% if user.is_authenticated %}
    <h1>Halo, {{request.user}}</h1>
    <h1>User Type : {{tipe}}</h1>
    {% else %}
    <h1>Hello, Please Login First</h1>
    {% endif %}
    {% if tipe == "Organizer" %}
    <!-- <table>
        <tr>
            <th>
                Email
            </th>
            <th>
                Waktu
            </th>
            <th>
                Tanggal
            </th>
            <th>
                No Dompet Digital
            </th>
            <th>
                Status
            </th>
            <th>
                Total Bayar
            </th>
            <th>
                ID Shared Profit
            </th>
        </tr>
        {% for i in row %}
        <tr>
            {% for j in i %}
            <td>
                {{j}}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table> -->
    <a href="/tambahevent">
        <button>Tambah Event +</button>
    </a>
    <h3>Your Event :</h3>
    <table style="border-spacing: 15px;">
        <tr>
            <th>
                ID Event
            </th>
            <th>
                Nama Event
            </th>
            <th>
                Tanggal Mulai
            </th>
            <th>
                Tanggal Selesai
            </th>
            <th>
                Jam Mulai
            </th>
            <th>
                Jam Selesai
            </th>
            <th>
                Deskripsi
            </th>
            <th>
                Kapasitas Total
            </th>
            <th>
                Kapasitas Total Tersedia
            </th>
            <th>
                Tipe Event
            </th>
            <th>
                Edit
            </th>
        </tr>
        {% for j in dataEvent %}
        <tr>
            {% for i in j %}
            {% if i == None %}
            <td>0</td>
            {% else %}
            <td>{{i}}</td>
            {% endif %}
            {% endfor %}
            <td>
                <button>
                    Tambah Kelas Tiket
                </button>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <br>
    <a href="/event">
        <button>
            Lihat Seluruh Daftar Event
        </button>
    </a>
    <!-- <h4>{{i}}</h4> -->
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'landingpage:login' %}">login</a>
    {% if user.is_authenticated %}
    <a href="{% url 'landingpage:logout' %}">logout</a>
    {% else %}
    <a href="{% url 'landingpage:pilihTipe' %}">register</a>
    {% endif %}
</body>
</html>

templates/landingpage/login.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event+</title>
</head>
<body>
    <div class="login">
        <div class="login-register-floating-box">
            <div class="login-register-header">
                <h1 class="title">Login</h1>
                <span>Login Event+</span>
            </div>
            <div class="login-register-form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-submit">Login</button>
                </form>
                <hr>
                <div class="other-choice">
                    <span>belum punya akun? Register <a href="{% url 'landingpage:pilihTipe' %}">disini</a></span>
                    <div class="google-OAuth2">
                    </div>
                <div>
            </div>
        </div>
    </div>
</body>
</html>

templates/landingpage/pilihTipe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event+</title>
</head>
<body>
    <div class="pilih-tipe">
        <h1>anda ingin mendaftar sebagai apa?</h1>
        <h2><a href="{% url 'landingpage:registerOrginazer' %}">Organizer</a></h2>
        <h2><a href="{% url 'landingpage:registerPengunjung' %}">Pengunjung</a></h2>
    </div>
</body>
</html>

templates/landingpage/registerOrganizer.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event+</title>
</head>
<body>
    <div class="register">
        <div class="login-register-floating-box">
            <div class="login-register-header">
                <h1 class="title">Sign Up</h1>
                <span>Daftar kan akun barumu disini</span>
            </div>
            <div class="login-register-form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="individu" required name="tipeOrgan" value="individu" onclick='opsi()'>
                        <label class="form-check-label" for="flexRadioDefault1" >
                            individu
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="perusahaan" required name="tipeOrgan" value="perusahaan" onclick="opsi()">
                        <label class="form-check-label" for="flexRadioDefault2">
                            perusahaan
                        </label>
                    </div>
                    <div id="form-opsi"></div></br>
                    <button type="submit" class="btn btn-submit">Sign Up</button>
                </form>
                <hr>
                <div class="other-choice">
                    <span>Sedah memiliki akun? Sign in <a href="{% url 'landingpage:login' %}">disini</a></span>
                    <div class="google-OAuth2">
                    </div>
                <div>
            </div>
        </div>
    </div>
</body>
<script>
    function opsi(){
        var individu = document.getElementById('individu');
        var perusahaan = document.getElementById('perusahaan');
        if( individu.checked == true ){
            document.getElementById('form-opsi').innerHTML = "";
            document.getElementById('form-opsi').innerHTML = 
                `</div><div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Depan</label></br>
                    <input type="text" name="namaDepan" class="form-control" required id="exampleFormControlInput1" placeholder="">
                </div>
                </div><div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Belakang</label></br>
                    <input type="text" name="namaBelakang" class="form-control" required id="exampleFormControlInput2" placeholder="">
                </div>
                </div><div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nomor KTP/NPWP</label></br>
                    <input type="text" name="nomor" class="form-control" required id="exampleFormControlInput3" placeholder="">
                </div>
                `
        }
        else if(perusahaan.checked == true){
            document.getElementById('form-opsi').innerHTML = "";
            document.getElementById('form-opsi').innerHTML = 
                `</div><div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Perusahaan</label></br>
                    <input type="text" name="namaDepan" class="form-control" required id="exampleFormControlInput1" placeholder="">
                </div>
                </div><div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nomor KTP/NPWP</label></br>
                    <input type="text" name="nomor" class="form-control" required id="exampleFormControlInput2" placeholder="">
                </div>
                `
        }
    }
</script>
</html>

templates/landingpage/registerPengunjung.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event+</title>
</head>
<body>
    <div class="register">
        <div class="login-register-floating-box">
            <div class="login-register-header">
                <h1 class="title">Sign Up</h1>
                <span>Daftar kan akun barumu disini</span>
            </div>
            <div class="login-register-form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Nama Depan</label></br>
                        <input type="text" name="namaDepan" class="form-control" id="exampleFormControlInput1" required placeholder="">
                    </div><div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Nama Belakang</label></br>
                        <input type="text" name="namaBelakang" class="form-control" id="exampleFormControlInput1" required placeholder="">
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Alamat</label></br>
                        <textarea class="form-control" id="exampleFormControlTextarea1" required rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-submit">Sign Up</button>
                </form>
                <hr>
                <div class="other-choice">
                    <span>Sedah memiliki akun? Sign in <a href="{% url 'landingpage:login' %}">disini</a></span>
                    <div class="google-OAuth2">
                    </div>
                <div>
            </div>
        </div>
    </div>
</body>
</html>

templates/landingpage/tambahevent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <br>
    <a href="../">
        <button>
            Back
        </button>
    </a>
    <br>
    <br>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="name">Nama Event:</label><br>
        <input type="text" id="name" name="name" required><br><br>
        <label for="tglmulai">Tanggal Mulai:</label><br>
        <input type="date" id="tglmulai" name="tglmulai" required><br><br>
        <label for="tglselesai">Tanggal Selesai:</label><br>
        <input type="date" id="tglselesai" name="tglselesai" required><br><br>
        <label for="jammulai">Jam Mulai:</label><br>
        <input type="time" id="jammulai" name="jammulai" required><br><br>
        <label for="jamselesai">Jam Selesai:</label><br>
        <input type="time" id="jamselesai" name="jamselesai" required><br><br>
        <label for="deskripsi">Deskripsi:</label><br>
        <input type="text" id="deskripsi" name="deskripsi" required><br><br>
        <h3>Tipe Event</h3>
        {% for i in row %}
        <input type="radio" id={{i}} name="tipe" value={{i.0}} required>
        <label for={{i}}>{{i.1}}</label><br><br>
        {% endfor %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>